language: python
virtualenv:
  system_site_packages: true
python:
  - "3.7.4"
cache: pip
install: pip install -r requirements.txt
script:
  - python -m pytest
after_success: coveralls
after_script: cd ~